name: Github Actions CI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v1
    - name: Compile file
      uses: xu-cheng/latex-action@master
      with:
        root_file: contributeurs-cheatshts.tex
        working_directory: 02_Cheatsheets/contributeurs/
    - name: Upload file
      run: |
        # configure git
        git config --global user.name "alec42"
        git config --global user.email "alecvanrassel@icloud.com"
        # setup ssh
        mkdir ~/.ssh
        chmod 700 ~/.ssh
        echo "$DEPLOY_KEY" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        git config --global core.sshCommand "ssh -i ~/.ssh/id_ed25519 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
        git clone --depth=1 --branch gh-pages git@github.com:xu-cheng/latex-tutorial.git "$GITHUB_WORKSPACE/deploy"
        cp -f 02_Cheatsheets/contributeurs/contributeurs-cheatshts.pdf "$GITHUB_WORKSPACE/deploy/contributeurs-cheatshts.pdf"
        cd "$GITHUB_WORKSPACE/deploy"
        git add contributeurs-cheatshts.pdf
        git commit -m "[github actions] deploy"
        git push
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
